### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by jvcorredor** [inkdropapp/inkdrop-live-export#6]
Description of issue:
Upon attempting to run live-export, I receive the follow error w/ stack trace:

```sh
file:///Users/jackhall/code-personal/void/node_modules/@inkdropapp/live-export/lib/index.js:27
        const headers = new Headers();
                        ^

ReferenceError: Headers is not defined
    at LiveExporter.callApi (file:///Users/jackhall/code-personal/void/node_modules/@inkdropapp/live-export/lib/index.js:27:25)
    at LiveExporter.getTags (file:///Users/jackhall/code-personal/void/node_modules/@inkdropapp/live-export/lib/index.js:61:21)
    at LiveExporter.start (file:///Users/jackhall/code-personal/void/node_modules/@inkdropapp/live-export/lib/index.js:277:33)
    at file:///Users/jackhall/code-personal/void/tools/import.mjs:16:18
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
error Command failed with exit code 1.
```

When looking in the compiled output in node_modules, I noticed that the `Headers` is in fact not found in the module:

```ts
import debug from 'debug';
import fs from 'fs';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkFrontmatter from 'remark-frontmatter';
import remarkStringify from 'remark-stringify';
import { visit } from 'unist-util-visit';
import yaml from 'js-yaml';

const logger = {
    debug: debug('inkdrop:export:debug'),
    info: debug('inkdrop:export:info'),
    error: debug('inkdrop:export:error')
};
const extractDocIdFromUri = (uri) => {
    const [, fileId] = uri.match(/inkdrop:\/\/([^\/]*)/) || [];
    return fileId;
};
class LiveExporter {
    constructor(config) {
        this.fileNameMap = {};
        this.tagMap = {};
        this.config = config;
    }
    async callApi(path, query = {}) {
        const { hostname, username, password, port } = this.config;
        const headers = new Headers();

...
```

I guess this is because the module was written using later version of node (17.5 with `--experimental-fetch`) than 16 where fetch is globally available, or perhaps some flag I am not using?

I was able to fix doing:

```
import fetch, { Headers } from 'node-fetch'

global.fetch = fetch
global.Headers = Headers
```

Please let me know the right way to fix this. Thanks.

**Comment by jvcorredor** [comment]
Also, I'm happy to bring in node-fetch as a dependency and submit the PR if you'd like.

**Comment by craftzdog** [comment]
Check the prerequisites https://github.com/inkdropapp/inkdrop-live-export#prerequisites
